language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - npm install
  - bower install
before_script:
  - grunt